apps/main/blog/urls.py
from django.urls import path

from apps.main.blog.views import blog, blog_detail
from apps.main.mainpage.views import *

app_name = "mainpage"

urlpatterns = [
    path('', blog, name='blog'),
    path('<slug:slug>/', blog_detail, name='blog-detail'),
]

apps/main/contact/urls.py
from django.urls import path

from apps.main.contact.views import contact, subscribe

app_name = "contact"

urlpatterns = [
    path('', contact, name='contact'),
    path('subscribe/', subscribe, name='subscribe'),
]

projem01/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from apps.main.contact.views import contact
from apps.main.mainpage.views import index
from projem01 import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('', include(('apps.main.mainpage.urls'), namespace='mainpage')),
    path('contact/', include(('apps.main.contact.urls'), namespace='contact')),
    path('reference/', include(('apps.main.reference.urls'), namespace='reference')),
    path('blog/', include(('apps.main.blog.urls'), namespace='blog')),
    path('super/user/admin', admin.site.urls),
    path('rosetta/lang/trans/', include('rosetta.urls')),
    path('i18n/', include('django.conf.urls.i18n'))
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0, maximum-scale=1, minimum-scale=1, target-densitydpi=device-dpi"
    >
    <title>{{ site_settings.text }}</title>
    <link rel="icon" type="image/png" href={% static "images/favicon.png" %}>
    <link rel="stylesheet" href={% static "css/font-awesome-pro.css" %}>
    <link rel="stylesheet" href={% static "css/bootstrap.min.css" %}>
    <link rel="stylesheet" href={% static "css/scroll_button.css" %}>
    <link rel="stylesheet" href={% static "css/plugin.css" %}>
    <link rel="stylesheet" href={% static "css/spacing.css" %}>
    <link rel="stylesheet" href={% static "css/style.css" %}>
    <link rel="stylesheet" href={% static "css/responsive.css" %}>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"/>

</head>

<body>


{% block header %}
    {% include 'partials/header.html' %}
{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}
    {% include 'partials/footer.html' %}
{% endblock %}


<script src={% static "js/plugin.js" %}></script>
<!--scroll button js-->
<script src={% static "js/scroll_button.js" %}></script>
<!--sticky sidebar js-->
<script src={% static "js/sticky_sidebar.js" %}></script>
<!-- Animation -->
<script src={% static "js/animation.js" %}></script>
<!--main/custom js-->
<script src={% static "js/main.js" %}></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

{% if messages %}
    {% for message in messages %}
        {% if forloop.last %}
            <script>
                Swal.fire({
                    position: 'center',
                    icon: '{{ message.tags }}',
                    title: '{{ message|safe }}',
                    showConfirmButton: false,
                    timer: 2500
                })
            </script>
        {% endif %}
    {% endfor %}
{% endif %}

{% for error_field, error_message in form.errors.items %}
    {% if forloop.lasr %}
        <script>
            Swal.fire({
                position: 'center',
                icon: 'warning',
                title: '{{ error_message|striptags }}',
                showConfirmButton: false,
                timer: 2500
            })
        </script>
    {% endif %}
{% endfor %}


</body>
</html>

templates/index.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}



{% block content %}
    <section id="about" class="tf__banner banner" style="background:url()">
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-xl-6 col-lg-8">
                    <div class="tf__banner_text">
                        <h1>
                            {{ main_page.slayt_text }}
                            <span class="cd-headline rotate-1">
                  <!-- ANIMATE TEXT VALUES: zoom, rotate-1, letters type, letters rotate-2, loading-bar, slide, clip, letters rotate-3, letters scale, push,  -->
                  <span class="cd-words-wrapper">
                    {% for item in main_page.slayt_skill.all %}
                        <b {% if forloop.first %}class="is-visible"{% endif %}>{{ item.text }}</b>
                    {% endfor %}
                  </span>
                </span>
                        </h1>
                        {{ main_page.slayt_content|safe }}
                        <ul>
                            <li>
                                <a class="common_btn" href="#"
                                >İndir Cv <i class="fa-solid fa-arrow-down-to-line"></i
                                ></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-xl-5 col-lg-4">
                    <div class="tf__banner_img">
                        <div class="img">
                            <img
                                    src="{{ main_page.slayt_image.url }}"
                                    alt="ZYAN"
                                    class="img-fluid w-100">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="tf__service pt_130 xs_pt_80" id="service">
        <div class="container">

            <div class="row">
                <div class="col-lg-9 m-auto">
                    <div class="tf__section_heading mb_40">
                        <h5 class="has-animation">{% trans "HİZMETLERİM" %}</h5>
                        <h2 class="has-animation">
                            {% blocktrans %}Aracılığıyla Hikayeler Oluşturmak, <br>
                                Tasarım ve Yenilik{% endblocktrans %}
                        </h2>
                    </div>
                </div>

            </div>
            <div class="row">
                {% for service in services %}
                    <div class="col-lg-4 col-md-6">
                        <div class="tf__single_service fade_left" data-trigerId="service">
                <span>
                    <img src="{{ service.logo.url }}" alt="{{ service.name }}" class="svg w-100">
                </span>
                            <h3>{{ service.name|safe }}</h3>
                            <p>{{ service.description|safe }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>


        </div>
    </section>
    <section class="tf__design mt_135 xs_mt_40 mb_120 xs_mb_80" id="contact">
        <div class="container">
            <div class="row">
                <div class="col-xl-6 col-lg-6">
                    <div class="tf__design_text">
                        <h2>{{ main_page.contact_text|safe }}</h2>
                        {{ main_page.contact_content|safe }}
                    </div>
                    <div class="row">
                        {% for item in main_page.contact_counter.all %}
                        <div class="col-xl-6 col-md-6">
                            <div
                                    class="tf__design_counter"
                                    data-trigerId="counter"
                            >

                                <h3><span class="counter">{{ item.count }}</span>{{ item.oid }}</h3>
                                <p>{{ item.text }}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-xl-6 col-lg-6">
                    <div class="tf__design_form">
                        <h2 class="has-animation">Buraya Dokun</h2>
                        <p class="">
                            Siteniz için onarımlarda tasarım tavsiyesi alarak her şeyi yapacağız
                            ve bakım Biz tercih edilenlerdeniz.
                        </p>
                        <form action="{% url "contact:contact" %}" method="post">
                            {% csrf_token %}
                            <input class="" type="text" placeholder="İsim" name="name">
                            <input class="" type="email" placeholder="Email" name="email">
                            <input class="" type="text" placeholder="Tel No" name="tel">
                            <textarea class="" rows="4" placeholder="Mesaj" name="message"></textarea>
                            <button type="submit" class="common_btn">Gönder</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="tf__skills pt_115 xs_pt_75 pb_70 xs_pb_30" id="skills">
        <div class="container">
            <div class="row">
                <div class="col-xl-10 col-lg-8 m-auto mb_60">
                    <div class="tf__section_heading mb_40">
                        <h5 class="has-animation">{% trans "Eğitim ve Beceri" %}</h5>
                        <h2 class="has-animation">
                            {% blocktrans %}Yeteneğinizi sergiliyoruz <br>
                                etkinizi güçlendirmek için{% endblocktrans %}
                        </h2>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for career in career_list %}
                    <div class="col-xl-6 col-lg-6">
                        <div
                                class="tf__single_skills fade_bottom"
                                data-trigerId="skills"
                                data-stagger=".13"
                        >
                            <span>{{ career.start_year }} - {{ career.finish_year }}</span>
                            <h3>{{ career.text }}</h3>
                            <p>{{ career.content }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="row">

                {% for skill in skill_list %}
                    <div class="col-xl-6 col-lg-6">

                        <div
                                class="tf__team_skills_bar_single fade_bottom"
                                data-trigerId="skills"
                                data-stagger=".25"
                        >
                            <p>{{ skill.text }}</p>
                            <div class="barfiller">
                                <div class="tipWrap">
                                    <span class="tip"></span>
                                </div>
                                <span class="fill" data-percentage="{{ skill.count }}"
                                      style="width: {{ skill.count }}%;"></span>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </section>
    <div class="tf__brand mt_120 xs_mt_80">
        <div class="row">
            <div class="col-12">
                <div class="marquee_animi">
                    <ul>
                        <li>* Recep</li>
                        <li>* ŞENGÜN</li>
                        <li>* İSTANBUL</li>
                        <li>* Yazılım</li>
                        <li>* Öğreniyor</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <section class="tf__blog pt_125 xs_pt_75 pb_40 xs_pb_0" id="blogs">
        <div class="container">
            <div class="row">
                <div class="col-xl-8 col-lg-9 mb_30">
                    <div class="tf__section_heading">
                        <h5 class="has-animation">{% trans "Bloğum" %}</h5>
                        <h2 class="has-animation">
                            {% trans "Kişisel Markanızın Potansiyelinin Kilidini Açmak" %}
                        </h2>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for blog in blog_list %}
                    <div class="col-xl-4 col-md-6">
                        <div class="tf__slingle_blog fade_left" data-trigerId="blogs">
                            <a href="{% url "blog:blog-detail" blog.slug %}" class="tf__blog_img"
                               data-cursor="read <br> more">
                                <img src="{{ blog.image.url }}" alt="{{ blog.slug }}" class="img-flid w-100">
                            </a>
                            <div class="tf__blog_text">
                                <span>{{ blog.date }}</span>
                                <ul>
                                    <li>
                                        <i class="fa-sharp fa-solid fa-circle-user"></i>
                                        {{ blog.user.username }}
                                    </li>
                                    <li>
                                        <i class="fa-sharp fa-solid fa-comments"></i>
                                        {% trans "Yorumlar" %} ({{ blog.comment_count }})
                                    </li>
                                </ul>
                                <a href="{% url "blog:blog-detail" blog.slug %}">{{ blog.text }}</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <div class="col-12">
                    <a href="{% url "blog:blog" %}" class="common_btn">{% trans "Daha Fazla Blog +" %}</a>
                </div>

            </div>
        </div>
    </section>
    <div class="tf__subscribe" style="background: url({% static "images/bg/subscribe.jpg" %})">
        <div class="tf__subscribe_overlay pt_115 xs_pt_75 pb_120 xs_pb_80">
            <div class="container">
                <div class="row">
                    <div class="col-xl-6 col-lg-8 col-md-10 m-auto">
                        <div class="tf__subscribe_text">
                            <h3 class="has-animation">{% trans "BÜLTENİME ABONE OLUN" %}</h3>
                            <form action="{% url "contact:subscribe" %}" method="post">
                                {% csrf_token %}
                                <input type="email" name="email" placeholder="{% trans "E Posta" %}">
                                <button type="submit" class="common_btn">{% trans "ABONE OL" %}</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}